apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobile-app-builder-api.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

{{- with .Values.environment }}
data:
  {{- toYaml . | nindent 2 }}
{{- end -}}