apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mobile-app-builder-api.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_USER: {{ default "" .Values.secrets.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ default "" .Values.secrets.DB_PASSWORD | b64enc | quote }}
  INTERNAL_TOKEN_SECRET: {{ (default (randAlphaNum 25) .Values.secrets.INTERNAL_TOKEN_SECRET) | b64enc | quote }}
  ACTUATOR_API_KEY: {{ default (randAlphaNum 10) .Values.global.actuatorApiKey | b64enc | quote }}