DELETE FROM resource_bundle where type='MOBILE' and locale = 'fr-FR';


INSERT INTO resource_bundle (uid, locale ,resource_key  ,resource_value, type,created_by,creation_date)
	VALUES
		(NEWID(),'fr-FR','ACTIVE_SESSION','Do you want to resume from one of your previous active session?_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','ALERT','ALERT_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Alert_Message','Do you really want to exit the application?_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Authentication_Failed','Authentication failed_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','CANCEL','CANCEL_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','BARCODE_ERROR','GS1 barcode scanning is not supported_FR','MOBILE','SUPER',GETDATE()),	
		(NEWID(),'fr-FR','CHECKBOX_ERROR_MESSAGE','Please select the checkbox_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','COMPONENT_ERROR','Invalid Format of Json!_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','CONNECTION_ERROR','Network unavailable! Please check the connection._FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DATEPICKER_ERROR_MESSAGE','Please select date_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DEFAULTFORM_ERROR','Form is not available_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DEFAULT_FORM_ERROR','Configure Default Form ID_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DROPDOWN_ERROR_MESSAGE','Please select any value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','ENTER_WAREHOUSE_NAME','Please Enter Valid Warehouse name_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','ENTRY_EMPTY_MESSAGE','Please enter the text_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','ERROR','Error_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','FIELD_IS_REQUIRED','This field is required_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Home','Home_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','INFO','INFO_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','INVALID_EMAIL','Invalid Email Id Pattern_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','INVALID_IMAGE_URL','Invalid image url_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','INVALID_NUMBER','Invalid Number Pattern_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','INVALID_TEXT','Invalid Text Pattern_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','LISTVIEW_ALERT','ListView does not have any values_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Logout_Alert','Do you really want to logout the application?_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MAXIMUM_LENGTH_MESSAGE','Value cannot exceed the maximum length_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MAXIMUM_VALUE_MESSAGE','Value cannot exceed the maximum value of_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MAXROWS','Maximum rows count already reached, could not add more rows_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MINIMUMTEXT','Field should match the minimum text length_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MINIMUM_LENGTH_MESSAGE','Value should match the minimum length_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MINIMUM_VALUE_MESSAGE','Value should match the minimum value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','MINROWS','Minimum rows requirement is not met_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','NO','No_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','OK_Message','OK_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','PAGE_ERROR','Server Error! Please try again later_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','QUESTIONNAIRE_INVALID_INPUT','Please enter valid input_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Required_FIELDS','Please fill the fields_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','SELECT_RADIO','Select radio_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','TIMEPICKER_ERROR_MESSAGE','Please select time_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','TIME_MATCH_MAX','Time should match the maximum value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','TIME_MAX_MESSAGE','Time should match the maximum value_FR','MOBILE','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','TIME_MIN_MESSAGE','Time should match the minimum value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','TIME_VALUE_MESSAGE','Time should match the minimum value and maximum value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','WARNING','WARNING_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Welcome','Welcome to application_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DECIMAL_VALUE','Enter Valid Decimal Value_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','YES','Yes_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','Active_Sessions','Active Sessions_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','DeviceID','DeviceID:_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','UserName','UserName_FR','MOBILE','SUPER',GETDATE()),
		(NEWID(),'fr-FR','LastAccessTime','LastAccessTime_FR','MOBILE','SUPER',GETDATE());
												