DELETE FROM resource_bundle where type='INTERNAL' and locale = 'en-US';

INSERT INTO resource_bundle (uid, locale ,resource_key  ,resource_value, type,created_by,creation_date)
	VALUES
		(NEWID(),'en-US','5001','Login authentication success','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5002','User logged in is authenticated','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9001','Login authentication failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9002','User access is not authorized','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9043','Login authentication failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9044','User authentication cannot be completed Authentication provider not responding.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6003','Login authentication failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6004','Authentication process failed to set/validate credentials','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9810','{0} version {1} is not compatible with {2} version {3}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5003','Flow created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5004','Flow created successfully with flowId : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9003','Flow creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9004','{0} is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6005','Flow creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6006','Flow creation failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9005','Flow creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9006','Flow creation failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5005','Flow updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5006','Flow updated successfully for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6007','Flow update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6008','Flow update failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9007','Flow update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9008','{0} is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9009','Flow update failed.Form name not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9010','{0} already exists. Form name is not unique for the flow.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9011','Flow update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9012','Flow update failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5007','Flow retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5008','Flow retrieved successfully for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6009','Flow not found','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6010','Flow not available for id : {0} ','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9013','Flow not found.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9014','Flow not available for id : {0} ','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9163','Flow is not published yet','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9164','Flow is disabled','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9180','Default form is disabled for this flow','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9181','Default form is not published yet for this flow','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9182','Flow has no default forms','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9183','Form not found','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5009','Flow status count retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5010','Flow status count retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6011','Flow status count retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6012','Flow status count retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9015','Flow status count retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9016','Flow status count retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5011','Flow list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5012','Flow list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6013','Flow retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6014','Flow retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9017','Flow retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9018','Flow retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5013','Flow unique validation done successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5014','{0} is unique.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5015','Successful checking of flow: ','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5016','{0} is not unique.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6015','Flow unique check validation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6016','Flow unique check validation failed for flow name : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5017','Flow deleted successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5018','Flow deleted successfully for flow id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6017','Flow deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6018','Flow deletion failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9019','Flow deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9020','Flow deletion failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5051','Form created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5052','Form created successfully with name : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9101','Form creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9102','Form name : {0} is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9103','Form creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9104','Form creation failed for name : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6101','Form creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6102','Form creation failed for name : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5053','Form updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5054','Form updated successfully for name : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9105','Form update is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9106','Form cannot be update.Form name : {0} is not unique.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9107','Form update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9108','Form update failed for name : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6103','Form update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6104','Form update failed for name : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5055','Form retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5056','Form retrieved successfully for Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9109','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9110','Form retrieved for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6105','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6106','Form retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5057','Form deleted successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5058','Form deleted successfully for Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9111','Form deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9112','Form deletion failed for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9113','Form deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9114','Form not available for Id : {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6107','Form deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6108','Form deletion failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),  		   

		(NEWID(),'en-US','5101','Menu created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5102','Menu created successfully for Product Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5103','Menu deleted successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5104','Menu deleted successfully for Product Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5115','Menu updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5116','Menu updated successfully for Product Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5107','No Menus are found','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5108','No Menus are found','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6201','Menu creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6202','Menu creation failed for Product Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9201','Menu creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9202','Menu creation failed for Product Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5105','Menu retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5106','Menu retrieved successfully for Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5109','Menu retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5110','No Menus available','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6203','Menu retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6204','Menu retrieved failed for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9203','Menu retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9204','Menu retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9205','Menu name is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9206','Menu name is already used in the warehouse','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9207','Menu deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9208','Menu deletion failed for menuId : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6205','Invalid data supplied','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6206','Invalid Menu Type supplied','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6207','Invalid : Menu Trigger Action','INTERNAL','SUPER',GETDATE()),
		 (NEWID(),'en-US','6208','Menu Unique Name Check encountered DataBase error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6209','Menu Trigger Action retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6210','Menu Trigger Action encountered DataBase error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6211','Menu Unique Name check retrieve unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6212','Trigger Action retrieval successful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6213','Menu Trigger Action retrieve unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6217','Menu deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6218','Menu deletion failed for menu Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9209','Menu Unique Name Check encountered  error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9210','Menu Trigger Action retrieval unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9211','Menu Trigger Action encountered  error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9213','Menu Unique Name check retrieval unsuccessful','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5151','Layer list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5152','Layer list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6301','Layer list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6302','Layer list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5153','User added to Layer successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5154','User added to Layer successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9251','User and Layer mapping failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9252','User and Layer mapping failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6303','User and Layer mapping failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6304','User and Layer mapping failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6913','User is already mapped to a Layer','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6914','User is already mapped to {0} Layer','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9954','User role mapping actionType is invalid','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9955','User role mapping actionType is invalid','INTERNAL','SUPER',GETDATE()),		
		(NEWID(),'en-US','5656','User sucessfully mapped as a super user','INTERNAL','SUPER',GETDATE()),				
		(NEWID(),'en-US','5657','User sucessfully mapped as a super user','INTERNAL','SUPER',GETDATE()),						
		(NEWID(),'en-US','6915','User is already mapped as a super user','INTERNAL','SUPER',GETDATE()),				
		(NEWID(),'en-US','6916','User is already mapped as a super user','INTERNAL','SUPER',GETDATE()),	
		(NEWID(),'en-US','5181','User and Layer association deleted successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5182','User and Layer association deleted successfully','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5155','User and Layer association updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5156','User and Layer association updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9253','User and Layer mapping update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9254','User and Layer mapping update failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6305','User and Layer mapping update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6306','User and Layer mapping update failed due to  database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5157','User Role retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5158','User Role retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9255','User Role retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9256','User Role retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5159','User Permissions retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5160','User Permissions retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9257','User Permissions retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9258','Permissions retrieval failed due to system error','INTERNAL','SUPER',GETDATE()), 


		(NEWID(),'en-US','5201','Application Config retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5202','Application Config retrieved successfully for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9301','Application Config retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9302','Application Config retrieval failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6351','Application Config retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6352','Application Config retrieval failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5203','Dashboard flows retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5204','Dashboard flows retrieved successfully for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9303','Dashboard flows retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9304','Dashboard flows retrieval failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6353','Dashboard flows retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6354','Dashboard flows retrieval failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5205','Product Configuration retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5206','ProductConfig Id retrieved successfully for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9305','Product Configuration retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9306','Product Configuration retrieval failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6355','Product Configuration retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6356','Product Configuration retrieval failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5251','Custom Component created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5252','Custom Component created successfully with id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9401','Custom Component creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9402','Custom Component creation failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6401','Custom Component creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6402','Custom Component creation failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5253','Custom Component list retrieved Successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5254','Custom Component list retrieved Successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9403','Custom Component retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9404','Custom Component retrieval failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6403','Custom Component retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6404','Custom Component retrieval failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5255','Custom Component updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5256','Custom Component updated successfully for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9405','Custom Component update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9406','Custom Component update failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6405','Custom Component update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6406','Custom Component update failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5257','Custom Component deleted successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5258','Custom Component deleted successfully for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9407','Custom Component deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9408','Custom Component deletion failed for : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6407','Custom Component deletion failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6408','Custom Component deletion failed for : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5299','Registry list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5300','Registry list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9501','Registry list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9502','Registry list retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6501','Registry list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6502','Registry list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5301','Registry retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5302','Registry retrieved successfully for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9503','Registry retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9504','Registry retrieval failed for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6503','Registry retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6504','Registry retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5303','Registry created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5304','Registry created for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9505','Registry creation is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9506','Registry creation failed. Registry name {0} is not unique for the given API type and current layer','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9507','Registry creation is unsuccessful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9508','Registry creation failed for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6505','Registry creation is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6506','Registry creation failed for : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5305','Registry updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5306','Registry updated for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9509','Registry update is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9510','Registry update failed. Registry name {0} is not unique for the given API type and current layer','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9511','Registry update is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9512','Registry update failed for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6507','Registry update is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6508','Registry update failed for : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5307','Registry deleted successfully for action {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5308','Registry deleted for id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9513','Registry deletion is unsuccessful for action {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9514','Registry deletion failed for : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6509','Registry deletion is unsuccessful for action {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6510','Registry deletion failed for : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5309','API Master Registry list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5310','API Master Registry list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9515','API Master Registry list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9516','API Master Registry list retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6511','API Master Registry list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6512','API Master Registry list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5311','API Registry retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5312','API Registry retrieved successfully for registry Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9517','API Registry retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9518','API Registry retrieval failed for registry Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6513','API Registry retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6514','API Registry retrieval failed for registry Id : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5313','APIs retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5314','APIs retrieved successfully for id  : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9519','APIs retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9520','APIs retrieval failed for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6515','APIs retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6516','APIs retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),

		--validateUser
		(NEWID(),'en-US','5161','User validated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5162','User is a valid user','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9259','User validation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9260','User ID is invalid','INTERNAL','SUPER',GETDATE()),

		--fetchAllForms
		(NEWID(),'en-US','5065','Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5066','Form list retrieved successfully for flow Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9125','Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9126','Form list retrieval failed for Id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6115','Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6116','Form list retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),		   

		--createDefaultForm
		(NEWID(),'en-US','5063','Form set as default successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5064','Form {0} set as default successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6113','Form set as default failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6114','Form set as default failed for id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9123','Form set as default failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9124','Form set as default failed for id : {0} due to system error','INTERNAL','SUPER',GETDATE()),

		--fetchOrphanForms
		(NEWID(),'en-US','5059','Orphan Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5060','Orphan Form list retrieved successfully for flow Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6109','Orphan Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6110','Orphan Form list retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9119','Orphan Form list retrieval is unsuccessful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9120','Orphan Form list retrieval is unsuccessful for Id : {0} encountered Database error.','INTERNAL','SUPER',GETDATE()),

		--fetchUnpublishForms
		(NEWID(),'en-US','5061','Unpublished Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5062','Unpublished Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9121','Unpublished Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9122','Unpublished Form list retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6111','Unpublished Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6112','Unpublished Form list retrieval failed due to Database error','INTERNAL','SUPER',GETDATE()),	
		
		(NEWID(),'en-US','5069','Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5070','Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6119','Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6120','Form list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9149','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9150','Form retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5351','Registry created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5352','Registry created successfully with registryId : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','9601','Registry creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9602','Registry creation failed due to system error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9956','Registry type is invalid','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9957','Registry type is invalid','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6601','Registry creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6602','Registry creation failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5353','Registry updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5354','Registry updated successfully for registry Id : {0}','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','9603','Registry update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9604','Registry update failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6603','Registry update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6604','Registry update failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5359','APIs override successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5360','APIs override successfully with below data','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','9605','APIs override failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9606','APIs override failed due to system error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6607','APIs override failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6608','APIs override failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5355','Registry name is unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5356','{0} is unique','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6917','Registry name is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6918','Registry creation failed. Registry name {0} is not unique for the given API type and current layer','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5400','Resource bundle retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5401','Resource bundle entries retrieved successfully','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6605','Registry name unique check failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6606','Registry name : {0} unique check failed due to system error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5163','User Layer retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5164','User Layer retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6309','User Layer retrival failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6310','User Layer retrival failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9261','User layer retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9262','User is not assigned with any layer','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','9807','Authentication failed for channel : {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9808','Authentication failed due to invalid channel : {0}','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9021','Flow update failed for flow name : {0}.','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9022','Flow update failed due to invalid action type : {0}','INTERNAL','SUPER',GETDATE()),
	     	   
	    (NEWID(),'en-US','5019','Flow validated successfully for flow id : {0}.','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5020','Unpublished forms can be present in this flow. Still Do you want publish form flow? ','INTERNAL','SUPER',GETDATE()),
	   
	    (NEWID(),'en-US','5021','Flow published successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5022','Flow published successfully with flow id : {0}','INTERNAL','SUPER',GETDATE()),

	      
		(NEWID(),'en-US','9023','Flow retrieval unsuccessful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9024','Flow retrieval unsuccessful as the flow with flowId: {0} is disabled.','INTERNAL','SUPER',GETDATE()),
		   
		   
		   (NEWID(),'en-US','5207','Defaultflow and Homeflow retrieved successfully','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','5208','Defaultflow and Homeflow retrieved successfully','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','9307','Defaultflow and Homeflow retrieval failed','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','9308','Defaultflow and Homeflow retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6357','Defaultflow and Homeflow retrieval failed','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6358','Defaultflow and Homeflow retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		   
		   (NEWID(),'en-US','6359','Home Flow not found','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6360','Home flow is disabled','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6361','Home flow is not published yet','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6362','Default form not found for home flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6363','Default form is disabled for home flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6364','Default form is not yet published for home flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6365','Default flow is disabled','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6366','Default flow is not published yet','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6367','Default form not found for default flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6368','Default form is disabled for default flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6369','Default form is not yet published for default flow','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'en-US','6372','Default Flow not found','INTERNAL','SUPER',GETDATE()),
	      (NEWID(),'en-US','6373','Default form of default flow is deleted','INTERNAL','SUPER',GETDATE()),
	       (NEWID(),'en-US','6374','Default from of home flow is deleted','INTERNAL','SUPER',GETDATE()),
		   
		  
		  (NEWID(),'en-US','5023','Flow disabled successfully','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','5024','Flow disabled successfully with flowId :{0}.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9025','Disable flow failed','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9026','Disable flow failed as the flow is the Default Flow.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9027','Disable flow failed','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9028','Disable flow failed as the flow is the Home Flow.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9029','Disable flow failed','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9030','Disable flow failed as the request type is invalid.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9031','disable flow failed','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9032','Disable flow failed as there are Forms under this flow.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','6019','Disable flow failed.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','6020','Disable flow failed due to database error.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9033','Disable flow failed.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9034','Disable flow failed due to system error.','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9160','Form is not published yet','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'en-US','9161','Form is disabled','INTERNAL','SUPER',GETDATE()),


		 --appconfig Creations

		(NEWID(),'en-US','5601','Context configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5602','Context configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5607','Global configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5608','Global configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5609','Application configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5610','Application configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5611','Internal configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5612','Internal configurations created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9901','Application configurations creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9902','Application configurations creation failed due to system  error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6901','Application configurations creation failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6902','Application configurations creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6907','Application configuration creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6908','Application configuration already exists for the supplied config type and name','INTERNAL','SUPER',GETDATE()),

		 --fetch appconfig based on type and name

		(NEWID(),'en-US','5603','Application configuration retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5604','Application configuration retrieved successfully for Type and Name : {0} {1}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9903','Application configuration retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9904','Application configuration retrieval failed for : {0} {1} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6903','Application configuration retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6904','Application configuration retrieval failed for : {0} {1} due to database error','INTERNAL','SUPER',GETDATE()),

		 --fetch appconfig based on type  
		 
		(NEWID(),'en-US','5605','Application configuration list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5606','Application configuration list retrieved successfully for type : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9905','Application configuration list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9906','Application configuration list retrieval failed for Type : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6905','Application configuration list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6906','Application configuration list retrieval failed for Type : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		
		--autocomplete appconfig based on type  

		(NEWID(),'en-US','5402','Application configuration retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5403','Application configuration retrieved successfully based on ConfigType Type : {0} search','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9703','Application configuration search failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9704','Application configuration search failed for Type : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6703','Application configuration search failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6704','Application configuration search failed for config type : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		
		--update appconfig Value 

		
		(NEWID(),'en-US','5613','Application configuration values updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5614','Application configuration values updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6909','Application configuration values update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6910','Application configuration values update failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9909','Application configuration values update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9910','Application configuration values update failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9913','Application configuration values update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9914','Application configuration values update failed as the name and type combination does not exist','INTERNAL','SUPER',GETDATE()),
		
		-- ClearConfig Value
		(NEWID(),'en-US','5615','Application configuration values cleared successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5616','Application configuration values cleared successfully' ,'INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6911','Clearing Application configuration values failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6912','Clearing ConfigValue failed due to database error.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9911','Clearing Application configuration values failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9912','Clearing Application configuration values failed due to system error','INTERNAL','SUPER',GETDATE()),

		--Product API invocation
		(NEWID(),'en-US','5651','Product API invocation successful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5652','Product API invocation successful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9950','Product API invocation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9951','Product API invocation unsuccessful due to {0}','INTERNAL','SUPER',GETDATE()),

		--fetchUnpublishOrphanForms
		(NEWID(),'en-US','5071','Unpublished Forms retrieval successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5072','Unpublished Forms retrieved successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5073','Orphan Forms retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5074','Orphan Forms retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9151','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9152','Form retrieval failed as the request type is invalid','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9153','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9154','Form retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),	
	    (NEWID(),'en-US','6121','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6122','Form retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
        
        --warehouselistapi
        (NEWID(),'en-US','5170','Warehouse list is retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5171','Warehouse details are fetched','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','6370','User Id is not present','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6371','Warehouse retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9165','Warehouse list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9166','Warehouse list encountered error.','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','6123','Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6124','Form list retrieval failed as the Flow with flow id : {0} is not available','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','6125','Form retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6126','No Forms available under the Flow','INTERNAL','SUPER',GETDATE()),
		
		
		(NEWID(),'en-US','9170','Invalid Action type','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9171','Form Action type is invalid: {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9172','Flow Action type is invalid: {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9133','Invalid identifier','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9134','Form Identifier is invalid: {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9174','Flow Identifier is invalid: {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9135','Flow has default form already','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9136','Flow has default form already. Do you want to override: {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9137','Form cannot be disabled','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9138','Default form cannot be disabled','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9145','Form validated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9146','Do you want to publish form ?','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9173','Form is disabled. Do you still want to publish the form?','INTERNAL','SUPER',GETDATE()),
		
		--publish forms
		(NEWID(),'en-US','5067','Form published successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5068','Form Published successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6117','Form publish failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6118','Form publish failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9147','Form publish failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9148','Form publish failed due to system error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9414','Custom Control creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9415','Custom Control name is not unique : {0}','INTERNAL','SUPER',GETDATE()),
		
		
      (NEWID(),'en-US','9080','Flow deletion failed','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'en-US','9081','Default FormFlow cannot be deleted','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'en-US','9082','Home FormFlow cannot be deleted.','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'en-US','9083','Formflow deletion will delete the forms inside it. Menus associated to the Formflow should be updated manually','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'en-US','9084','Formflow validated successfully','INTERNAL','SUPER',GETDATE()),
	  
	    (NEWID(),'en-US','5029','Flow Extended successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5030','Flow Extended successfully with flowId : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5047','Flow cloned successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5048','Flow cloned successfully with flowId : {0}','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9046','Flow Extension creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9047','{0}, Extended Flow Name is not unique','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6025','Flow Extension creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6026','Flow Extension creation failed due to database error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','6033','Cloning of flow failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6034','Cloning of flow failed due to database error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9048','Flow Extension creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9049','Flow Extension creation failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9066','Cloning of flow failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9067','Cloning of flow failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9070','Flow version creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9071','Flow version created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9072','Flow version creation failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9073','Flow version creation failed due to system error','INTERNAL','SUPER',GETDATE()),

	    (NEWID(),'en-US','5035','Form Extended successfully','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'en-US','5036','Form Extended successfully with formId : {0} within the same flow','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5037','Form Extended successfully','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'en-US','5038','Form Extended successfully with formId : {0} in the different flow','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9054','Extending component Unsuccessful.','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'en-US','9055','Extending component Unsuccessful as the request type is Invalid.','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9056','Form Extension creation failed','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9057','{0}, Extended form Name is not unique','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5031','Flow Extension retrieved successfully.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5032','Flow Extension difference retrieved successfully for parent : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5033','Flow Extension cannot retrieved successfully.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5034','Flow Extension difference cannot be retrieved for parent : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9050','Flow Extension history retrieval is encountered error.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9051','Flow Extension retrieval is unsuccessful for extension type : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6027','Flow Extension history retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6028','Flow Extension history retrieval failed for object id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9052','Flow Extension history retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9053','Flow Extension history retrieval failed for object id : {0} due to system error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5452','Resource bundle retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5453','Resource bundles based on locale and type retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9803','Resource bundle retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9804','Resource bundle retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6803','Resource bundle retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6804','Resource bundle retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),	   
		(NEWID(),'en-US','5450','Resource bundle created successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5451','Resource bundle created successfully with id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6801','Resource bundle creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6802','Resource bundle creation failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9801','Resource bundle creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9802','Resource bundle creation failed due to system error','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'en-US','6807','Resource bundle creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6808','Resource bundles based on locale and key pair is already exist','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'en-US','6809','Resource bundle creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6810','Resource bundles resource key is not allowed to empty string','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'en-US','9129','Invalid Identifier','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9130','Invalid Identifier passed while marking default','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9128','Flow has already default form associated','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9127','Creating default form failed','INTERNAL','SUPER',GETDATE()),
		     
		(NEWID(),'en-US','5653','File imported successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5654','All Files Imported Successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5659','Imported data saved successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5660','All files imported are saved successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5661','All files imported are published successfully','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9952','File import failed','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9953','File import failed due to system error','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9960','File import failed for {0}','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','9961','File Import failed for {0}. Empty Upload file is not allowed','INTERNAL','SUPER',GETDATE()),		  
   	    (NEWID(),'en-US','9967','Data save failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9968','Imported data failed during save due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9969','Import data check violated','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9970','Rules to import data violated. {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9971','File Import should be from root folder','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9972','Nested folder file import is not allowed, File import should be from root folder. {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5701','Comparison disallowed for {0}.','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5702','This {0} requested for comparison is newly added in the extended form and doesn’t exist in the parent form','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5709','Comparison failed for {0}.','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'en-US','5710','Parent field is missing to compare.','INTERNAL','SUPER',GETDATE()),
	    
		(NEWID(),'en-US','5039','Flow basic details retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5040','Flow basic details retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9058','Flow basic details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9059','Flow basic details retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6029','Flow basic details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6030','Flow basic details retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5801','Locale updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5802','Locale updated successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5803','Invalid Locale supplied.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5804','Invalid Locale supplied.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5805','Locale update encountered database error.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5806','Locale update encountered database error.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5807','Locale update failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5808','Locale update failed due to database error','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5500','Flow is deleted','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5502','Form is deleted.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5504','Default form is not available for this flow','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5506','Custom Control is deleted','INTERNAL','SUPER',GETDATE()),

		
		(NEWID(),'en-US','5111','Invalid product name','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5112','Warehouse name is not valid','INTERNAL','SUPER',GETDATE()),
		
		
		--fetchOrphanForms
		(NEWID(),'en-US','5080','Custom Component Form list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5081','Custom Component Form list retrieved successfully for flow Id : {0}','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6150','Custom Component Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6151','Custom Component Form list retrieval failed for Id : {0} due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9155','Custom Component Form list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9156','Custom Component Form list retrieval failed for Id : {0} due to system error.','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','5025','Logout successful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5026','User Logged out Successfully','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','6214','Invalid Request','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6215','Product Name or Default warehouse is mandatory','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','9409','Custom Control validation successful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9410','Custom Control is linked with forms , Do you still want to delete ?','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9411','Custom Control validation successful','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9412','Do you want to delete ?','INTERNAL','SUPER',GETDATE()),
		
		--fetch hotkeys
		
		(NEWID(),'en-US','5703','Hot key list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5704','Hot key list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9958','Hot key list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9959','Hot key list retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6919','Hot key list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6920','Hot key list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		
		
			--fetch user language codes
		
		(NEWID(),'en-US','5705','User language code list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5706','User language code list retrieved successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9962','User language code list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9963','User language code list retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6921','User language code list retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6922','User language code list retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),
		
		-- Pre and Post processor file upload
		(NEWID(),'en-US','9964','Both pre and post processor files are empty','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9965','{0} processor file upload failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6923','{0} processor file upload failed due to database error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5707','{0} processor file uploaded successfully','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9966','API has already {0} processor file','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5708','API do not have any {0} processor file','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5041','Flow with Default Form details retrieval Successful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5042','Flow with Default Form details retrieved Successfully.','INTERNAL','SUPER',GETDATE()),		
		(NEWID(),'en-US','9060','Flow with Default Form details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9061','Flow with Default Form details retrieval failed as Flow Permissions are Invalid','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9062','Flow with Default Form details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9063','Flow with Default Form details retrieval failed due to system error','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9064','Form details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9065','Form details retrieval Unsuccessful as the Flow with id : {0} has No Permissions.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6031','Flow with Default Form details retrieval failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6032','Flow with Default Form details retrieval failed due to database error','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5043','Tenant session inactive period retrival Successful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5044','Tenant session inactive period retrived Successfully.','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'en-US','5045','Tenant session inactive period modified Successful.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','5046','Tenant session inactive period modified Successfully.','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'en-US','6609','Registry creation failed','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6610','Uploading Swagger file is either in Invalid Format or Open API Version is not supported ','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','6611','Third party API - Host is mandatory','INTERNAL','SUPER',GETDATE()),
		
		-- Product validity check during login/auth
		(NEWID(),'en-US','9973','Invalid product {0}.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'en-US','9974','Invalid product {0} supplied. This product is not supported by current instance of BFFCORE.','INTERNAL','SUPER',GETDATE());