DELETE FROM resource_bundle where type='MOBILE' and locale = 'en-US';


INSERT INTO resource_bundle (uid, locale ,resource_key  ,resource_value, type,created_by,creation_date)
	VALUES
		(NEWID(),'en-US','ACTIVE_SESSION','Do you want to resume from one of your previous active session?','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','ALERT','ALERT','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Alert_Message','Do you really want to exit the application?','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Authentication_Failed','Authentication failed','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','CANCEL','CANCEL','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','BARCODE_ERROR','GS1 barcode scanning is not supported','MOBILE','SUPER',GETDATE()),	
		(NEWID(),'en-US','CHECKBOX_ERROR_MESSAGE','Please select the checkbox','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','COMPONENT_ERROR','Invalid Format of Json!','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','CONNECTION_ERROR','Network unavailable! Please check the connection.','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DATEPICKER_ERROR_MESSAGE','Please select date','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DEFAULTFORM_ERROR','Form is not available','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DEFAULT_FORM_ERROR','Configure Default Form ID','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DROPDOWN_ERROR_MESSAGE','Please select any value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','ENTER_WAREHOUSE_NAME','Please Enter Valid Warehouse name','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','ENTRY_EMPTY_MESSAGE','Please enter the text','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','ERROR','Error','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','FIELD_IS_REQUIRED','This field is required','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Home','Home','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','INFO','INFO','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','INVALID_EMAIL','Invalid Email Id Pattern','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','INVALID_IMAGE_URL','Invalid image url','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','INVALID_NUMBER','Invalid Number Pattern','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','INVALID_TEXT','Invalid Text Pattern','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','LISTVIEW_ALERT','ListView does not have any values','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Logout_Alert','Do you really want to logout the application?','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MAXIMUM_LENGTH_MESSAGE','Value cannot exceed the maximum length','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MAXIMUM_VALUE_MESSAGE','Value cannot exceed the maximum value of','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MAXROWS','Maximum rows count already reached, could not add more rows','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MINIMUMTEXT','Field should match the minimum text length','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MINIMUM_LENGTH_MESSAGE','Value should match the minimum length','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MINIMUM_VALUE_MESSAGE','Value should match the minimum value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','MINROWS','Minimum rows requirement is not met','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','NO','No','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','OK_Message','OK','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','PAGE_ERROR','Server Error! Please try again later','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','QUESTIONNAIRE_INVALID_INPUT','Please enter valid input','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Required_FIELDS','Please fill the fields','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','SELECT_RADIO','Select radio','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','TIMEPICKER_ERROR_MESSAGE','Please select time','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','TIME_MATCH_MAX','Time should match the maximum value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','TIME_MAX_MESSAGE','Time should match the maximum value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','TIME_MIN_MESSAGE','Time should match the minimum value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','TIME_VALUE_MESSAGE','Time should match the minimum value and maximum value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','WARNING','WARNING','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Welcome','Welcome to application','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DECIMAL_VALUE','Enter Valid Decimal Value','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','YES','Yes','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','Active_Sessions','Active Sessions','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','DeviceID','DeviceID:','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','UserName','UserName','MOBILE','SUPER',GETDATE()),
		(NEWID(),'en-US','LastAccessTime','LastAccessTime','MOBILE','SUPER',GETDATE());
												