--All tables clean-up
DELETE FROM resource_bundle;

DELETE FROM version_mapping;
DELETE FROM version_master;

DELETE FROM LOCALE;

DELETE FROM key_code_master;

DELETE FROM APP_CONFIG_DETAIL;
DELETE FROM APP_CONFIG_MASTER;

DELETE FROM MENU_TYPE;

DELETE FROM API_MASTER;
DELETE FROM API_REGISTRY;

DELETE FROM PRODUCT_CONFIG;
DELETE FROM ROLE_PRIVILEGE;				
DELETE FROM PRIVILEGE_MASTER;
DELETE FROM MASTER_USER;
DELETE FROM ROLE_MASTER;

DELETE FROM PRODUCT_PROPERTIES WHERE PRODUCT_ID IN (SELECT UID FROM PRODUCT_MASTER WHERE NAME = 'WMS');
DELETE FROM PRODUCT_DATA_SOURCE_MASTER WHERE PRODUCT_ID IN (SELECT UID FROM PRODUCT_MASTER WHERE NAME = 'WMS');;
DELETE FROM PRODUCT_MASTER WHERE NAME = 'WMS';

--Product base tables clean-up and insert base data

INSERT INTO PRODUCT_MASTER (UID, NAME ,CONFIG_PROPERTIES,SCHEME,CONTEXT_PATH,PORT,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'WMS','TEST','http','3.13.173.174','4500','SUPER', GETDATE());
                
INSERT INTO PRODUCT_DATA_SOURCE_MASTER (UID, NAME , BASE_PATH,CONTEXT_PATH, PORT, PRODUCT_ID)
                VALUES(NEWID(),'test_name','10.0.0.0', '/test', 8080, (SELECT UID FROM PRODUCT_MASTER WHERE NAME = 'WMS'));

INSERT INTO PRODUCT_PROPERTIES (UID,IS_PRIMARY_REF,IS_SECONDARY_REF,NAME,PROP_VALUE,PRODUCT_ID, CREATED_BY, CREATION_DATE)
				VALUES (NEWID(), 0 ,1 ,'WMS','___' , (SELECT UID FROM PRODUCT_MASTER WHERE NAME = 'WMS'), 'SUPER', GETDATE());
		
                
--Authorization tables clean-up


-- INSERT MASTER LIST OF LAYERS
INSERT INTO ROLE_MASTER (UID, LEVEL, NAME, CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),0,'JDA Product Development', 'SUPER', GETDATE());  
INSERT INTO ROLE_MASTER (UID, LEVEL,NAME, CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),1,'JDA Services', 'SUPER', GETDATE());
INSERT INTO ROLE_MASTER (UID, LEVEL, NAME, CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),2, 'Third Party Implementor', 'SUPER', GETDATE());
INSERT INTO ROLE_MASTER (UID, LEVEL, NAME, CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),3, 'Customer', 'SUPER', GETDATE());
				
--PRODUCT CONFIGURATION FOR DEFAULT WAREHOUSE
				 
INSERT INTO PRODUCT_CONFIG (UID, SECONDARY_REF_ID, VERSION_ID, ROLE_ID)
 VALUES (NEWID(), (SELECT UID FROM PRODUCT_PROPERTIES WHERE PROP_VALUE = '___'),'0',
		(SELECT UID FROM ROLE_MASTER WHERE NAME ='JDA Product Development'))
INSERT INTO PRODUCT_CONFIG (UID, SECONDARY_REF_ID, VERSION_ID, ROLE_ID)
 VALUES (NEWID(), (SELECT UID FROM PRODUCT_PROPERTIES WHERE PROP_VALUE = '___'),'0',
		(SELECT UID FROM ROLE_MASTER WHERE NAME ='JDA Services'))	
INSERT INTO PRODUCT_CONFIG (UID, SECONDARY_REF_ID, VERSION_ID, ROLE_ID)
 VALUES (NEWID(), (SELECT UID FROM PRODUCT_PROPERTIES WHERE PROP_VALUE = '___'),'0',
		(SELECT UID FROM ROLE_MASTER WHERE NAME ='Third Party Implementor'))	
INSERT INTO PRODUCT_CONFIG (UID, SECONDARY_REF_ID, VERSION_ID, ROLE_ID)
 VALUES (NEWID(), (SELECT UID FROM PRODUCT_PROPERTIES WHERE PROP_VALUE = '___'),'0',
		(SELECT UID FROM ROLE_MASTER WHERE NAME ='Customer'))					

--SUPER USER SCRIPT
INSERT INTO MASTER_USER (uid, user_id,created_by, creation_date) VALUES (NEWID(), 'SUPER', 'SUPER', GETDATE());				


--insert privileges in Privilege master table
				
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'CREATE_FORMFLOW', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'READ_FORMFLOW', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'UPDATE_FORMFLOW', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'DELETE_FORMFLOW', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'PUBLISH_FORMFLOW', 'SUPER', GETDATE());

INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'CREATE_FORM', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'READ_FORM', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'UPDATE_FORM', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'DELETE_FORM', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'PUBLISH_FORM', 'SUPER', GETDATE());
				
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'CREATE_MENU', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'READ_MENU', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'UPDATE_MENU', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'DELETE_MENU', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)

                VALUES(NEWID(),'CREATE_CUSTOM_CONTROL', 'SUPER', GETDATE());	
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'READ_CUSTOM_CONTROL', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'UPDATE_CUSTOM_CONTROL', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
                VALUES(NEWID(),'DELETE_CUSTOM_CONTROL', 'SUPER', GETDATE());
INSERT INTO PRIVILEGE_MASTER (UID, NAME,CREATED_BY, CREATION_DATE)
				VALUES(NEWID(),'EXTEND_FORMFLOW', 'SUPER', GETDATE());					

--Role-Privilege mapping master table
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Product Development'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'EXTEND_FORMFLOW'));


				 
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='JDA Services'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'EXTEND_FORMFLOW'));
				 

INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Third Party Implementor'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'EXTEND_FORMFLOW'));
		

INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORMFLOW'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'PUBLISH_FORM'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_MENU'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'CREATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'READ_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'UPDATE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'DELETE_CUSTOM_CONTROL'));
INSERT INTO ROLE_PRIVILEGE (UID, ROLE_ID, PRIVILEGE_ID) 
VALUES (NEWID(), (SELECT UID FROM ROLE_MASTER WHERE NAME='Customer'), (
				 SELECT UID FROM PRIVILEGE_MASTER WHERE NAME = 'EXTEND_FORMFLOW'));

			 

--Menu Type clean-up and insertion

INSERT INTO MENU_TYPE (UID,MENU_TYPE) VALUES  (NEWID(),'MAIN');
INSERT INTO MENU_TYPE (UID,MENU_TYPE) VALUES  (NEWID(),'GLOBAL_CONTEXT');
INSERT INTO MENU_TYPE (UID,MENU_TYPE) VALUES  (NEWID(),'FORM_CONTEXT');
INSERT INTO MENU_TYPE (UID,MENU_TYPE) VALUES  (NEWID(),'BOTTOM_BAR');


-- APP Config clean-up and predefined Global and Application variable entries for Mobile configuration

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'WarehouseName','GLOBAL', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'DeviceID','GLOBAL', 'SUPER', GETDATE());  

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'PLACEHOLDERFONT','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'16', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='PLACEHOLDERFONT' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'PLACEHOLDERCOLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#A9A9A9', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='PLACEHOLDERCOLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'ERRORFONT','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'16', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='ERRORFONT' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'ERRORCOLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#FF0000', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='ERRORCOLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'LABELFONT','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'16', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='LABELFONT' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'LABELCOLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#0000FF', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='LABELCOLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'HINTFONT','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'14', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='HINTFONT' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'HINTCOLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#A9A9A9', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='HINTCOLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'LEFTPADDING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='LEFTPADDING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'RIGHTPADDING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='RIGHTPADDING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'CENTREPADDING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='CENTREPADDING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'SPACING_LABELNCONTROL','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='SPACING_LABELNCONTROL' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'CONTROLSPACING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'30', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='CONTROLSPACING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'IMAGECACHEDURATION','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'45', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='IMAGECACHEDURATION' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'SEPARATORHEIGHT','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'1', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='SEPARATORHEIGHT' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'SEPARATORCOLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#D3D3D3', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='SEPARATORCOLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'SEPARATORSPACING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='SEPARATORSPACING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'TOPPADDING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='TOPPADDING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'BOTTOMPADDING','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='BOTTOMPADDING' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'TOPMARGIN','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='TOPMARGIN' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'BOTTOMMARGIN','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='BOTTOMMARGIN' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'LEFTMARGIN','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='LEFTMARGIN' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'RIGHTMARGIN','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'10', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='RIGHTMARGIN' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'FLOATINGLABEL_FONTSIZE','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'14', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='FLOATINGLABEL_FONTSIZE' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'FLOATINGLABEL_COLOR','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'#0000FF', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='FLOATINGLABEL_COLOR' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

INSERT INTO APP_CONFIG_MASTER (UID,CONFIG_NAME,CONFIG_TYPE,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'STYLE','APPLICATION', 'SUPER', GETDATE());
INSERT INTO APP_CONFIG_DETAIL (UID,CONFIG_VALUE,APP_CONFIG_MASTER_UID,CREATED_BY, CREATION_DATE) VALUES  (NEWID(),'Outlined', (SELECT UID FROM APP_CONFIG_MASTER WHERE CONFIG_NAME='STYLE' AND CONFIG_TYPE='APPLICATION'), 'SUPER', GETDATE());

--ORCHESTRATION API REGISTRY FOR ALL LAYERS
INSERT INTO api_registry
           (uid
           ,api_type
           ,api_version
           ,base_path
           ,context_path
           ,created_by
           ,creation_date
           ,helper_class
           ,name
           ,port
           ,version_id
           ,role_id)
     VALUES
           (NEWID()
           ,'ORCHESTRATION'
           ,'1.0'
           ,'http://0.0.0.0'
           ,'/test'
           ,'SUPER'
           ,GETDATE()
           ,null
           ,'Orchestration'
           ,'80'
           ,'1'
           , (select uid from role_master where level = 0));

INSERT INTO api_registry
           (uid
           ,api_type
           ,api_version
           ,base_path
           ,context_path
           ,created_by
           ,creation_date
           ,helper_class
           ,name
           ,port
           ,version_id
           ,role_id)
     VALUES
           (NEWID()
           ,'ORCHESTRATION'
           ,'1.0'
           ,'http://0.0.0.0'
           ,'/test'
           ,'SUPER'
           ,GETDATE()
           ,null
           ,'Orchestration'
           ,'80'
           ,'1'
           , (select uid from role_master where level = 1));

INSERT INTO api_registry
           (uid
           ,api_type
           ,api_version
           ,base_path
           ,context_path
           ,created_by
           ,creation_date
           ,helper_class
           ,name
           ,port
           ,version_id
           ,role_id)
     VALUES
           (NEWID()
           ,'ORCHESTRATION'
           ,'1.0'
           ,'http://0.0.0.0'
           ,'/test'
           ,'SUPER'
           ,GETDATE()
           ,null
           ,'Orchestration'
           ,'80'
           ,'1'
           , (select uid from role_master where level = 2));

INSERT INTO api_registry
           (uid
           ,api_type
           ,api_version
           ,base_path
           ,context_path
           ,created_by
           ,creation_date
           ,helper_class
           ,name
           ,port
           ,version_id
           ,role_id)
     VALUES
           (NEWID()
           ,'ORCHESTRATION'
           ,'1.0'
           ,'http://0.0.0.0'
           ,'/test'
           ,'SUPER'
           ,GETDATE()
           ,null
           ,'Orchestration'
           ,'80'
           ,'1'
           , (select uid from role_master where level = 3));

--Delete existing hoty keys if any           
Delete from key_code_master;
           
-- Script for Hot Key Global
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F1','KEYCODE_F1','','131','0','0','0','0','GLOBAL',1, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Funtion_F1','ALT + KEYCODE_F1','','131','0','0','1','0','GLOBAL',2, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Funtion_F1','CTRL + KEYCODE_F1','','131','1','0','0','0','GLOBAL',3, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shift_Funtion_F1','SHFT + KEYCODE_F1','','131','0','1','0','0','GLOBAL',4, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F2','KEYCODE_F2','','132','0','0','0','0','GLOBAL',5, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Funtion_F2','ALT + KEYCODE_F2','','132','0','0','1','0','GLOBAL',6, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Funtion_F2','CTRL + KEYCODE_F2','','132','1','0','0','0','GLOBAL',7, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shift_Funtion_F2','SHFT + KEYCODE_F2','','132','0','1','0','0','GLOBAL',8, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F3','KEYCODE_F3','','133','0','0','0','0','GLOBAL',9, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Funtion_F3','ALT + KEYCODE_F3','','133','0','0','1','0','GLOBAL',10, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Funtion_F3','CTRL + KEYCODE_F3','','133','1','0','0','0','GLOBAL',11, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shift_Funtion_F3','SHFT + KEYCODE_F3','','133','0','1','0','0','GLOBAL',12, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F4','KEYCODE_F4','','134','0','0','0','0','GLOBAL',13, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Funtion_F4','ALT + KEYCODE_F4','','134','0','0','1','0','GLOBAL',14, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Funtion_F4','CTRL + KEYCODE_F4','','134','1','0','0','0','GLOBAL',15, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shift_Funtion_F4','SHFT + KEYCODE_F4','','134','0','1','0','0','GLOBAL',16, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F5','KEYCODE_F5','','135','0','0','0','0','GLOBAL',17, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Funtion_F5','ALT + KEYCODE_F5','','135','0','0','1','0','GLOBAL',18, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Funtion_F5','CTRL + KEYCODE_F5','','135','1','0','0','0','GLOBAL',19, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shift_Funtion_F5','SHFT + KEYCODE_F5','','135','0','1','0','0','GLOBAL',20, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F6','KEYCODE_F6','','136','0','0','0','0','GLOBAL',21, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F7','KEYCODE_F7','','137','0','0','0','0','GLOBAL',22, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F8','KEYCODE_F8','','138','0','0','0','0','GLOBAL',23, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F9','KEYCODE_F9','','139','0','0','0','0','GLOBAL',24, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F10','KEYCODE_F10','','140','0','0','0','0','GLOBAL',25, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F11','KEYCODE_F11','','141','0','0','0','0','GLOBAL',26, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Funtion_F12','KEYCODE_F12','','142','0','0','0','0','GLOBAL',27, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'V','V','','50','0','0','0','0','GLOBAL',28, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_V','ALT+V','','50','0','0','1','0','GLOBAL',29, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_V','SHFT+V','','50','0','1','0','0','GLOBAL',30, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_V','CTRL+V','','50','1','0','0','0','GLOBAL',31, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'W','W','','51','0','0','0','0','GLOBAL',32, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_W','ALT+W','','51','0','0','1','0','GLOBAL',33, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_W','CTRL+W','','51','1','0','0','0','GLOBAL',34, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'X','X','','52','0','0','0','0','GLOBAL',35, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_X','ALT+X','','52','0','0','1','0','GLOBAL',36, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_X','SHFT+X','','52','0','1','0','0','GLOBAL',37, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_X','CTRL+X','','52','1','0','0','0','GLOBAL',38, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Y','Y','','53','0','0','0','0','GLOBAL',39, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Y','ALT+Y','','53','0','0','1','0','GLOBAL',40, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_Y','SHFT+Y','','53','0','1','0','0','GLOBAL',41, 'SUPER', GETDATE());

-- Script for Hot Key Context
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'A','A','','29','0','0','0','0','CONTEXT',1, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_A','ALT+A','','29','0','0','1','0','CONTEXT',2, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_A','SHFT+A','','29','0','1','0','0','CONTEXT',3, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_A','CTRL+A','','29','1','0','0','0','CONTEXT',4, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'B','B','','30','0','0','0','0','CONTEXT',5, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_B','ALT+B','','30','0','0','1','0','CONTEXT',6, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_B','SHFT+B','','30','0','1','0','0','CONTEXT',7, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_B','CTRL+B','','30','1','0','0','0','CONTEXT',8, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'C','C','','31','0','0','0','0','CONTEXT',9, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_C','ALT+C','','31','0','0','1','0','CONTEXT',10, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_C','SHFT+C','','31','0','1','0','0','CONTEXT',11, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_C','CTRL+C','','31','1','0','0','0','CONTEXT',12, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'D','D','','32','0','0','0','0','CONTEXT',13, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_D','ALT+D','','32','0','0','1','0','CONTEXT',14, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_D','SHFT+D','','32','0','1','0','0','CONTEXT',15, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_D','CTRL+D','','32','1','0','0','0','CONTEXT',16, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_E','ALT+E','','33','0','0','1','0','CONTEXT',17, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_E','SHFT+E','','33','0','1','0','0','CONTEXT',18, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_E','CTRL+E','','33','1','0','0','0','CONTEXT',19, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Meta_E','META+E','','33','0','0','0','1','CONTEXT',20, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'F','F','','34','0','0','0','0','CONTEXT',21, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_F','ALT+F','','34','0','0','1','0','CONTEXT',22, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_F','SHFT+F','','34','0','1','0','0','CONTEXT',23, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_F','CTRL+F','','34','1','0','0','0','CONTEXT',24, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'G','G','','35','0','0','0','0','CONTEXT',25, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_G','ALT+G','','35','0','0','1','0','CONTEXT',26, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_G','SHFT+G','','35','0','1','0','0','CONTEXT',27, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_G','CTRL+G','','35','1','0','0','0','CONTEXT',28, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'H','H','','36','0','0','0','0','CONTEXT',29, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_H','ALT+H','','36','0','0','1','0','CONTEXT',30, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_H','SHFT+H','','36','0','1','0','0','CONTEXT',31, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_H','CTRL+H','','36','1','0','0','0','CONTEXT',32, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'I','I','','37','0','0','0','0','CONTEXT',33, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_I','ALT+I','','37','0','0','1','0','CONTEXT',34, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_I','SHFT+I','','37','0','1','0','0','CONTEXT',35, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_I','CTRL+I','','37','1','0','0','0','CONTEXT',36, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'J','J','','38','0','0','0','0','CONTEXT',37, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_J','ALT+J','','38','0','0','1','0','CONTEXT',38, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_J','SHFT+J','','38','0','1','0','0','CONTEXT',39, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_J','CTRL+J','','38','1','0','0','0','CONTEXT',40, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'K','K','','39','0','0','0','0','CONTEXT',41, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_K','ALT+K','','39','0','0','1','0','CONTEXT',42, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_K','SHFT+K','','39','0','1','0','0','CONTEXT',43, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_K','CTRL+K','','39','1','0','0','0','CONTEXT',44, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_L','ALT+L','','40','0','0','1','0','CONTEXT',45, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_L','SHFT+L','','40','0','1','0','0','CONTEXT',46, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_L','CTRL+L','','40','1','0','0','0','CONTEXT',47, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Meta_L','META+L','','40','0','0','0','1','CONTEXT',48, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'M','M','','41','0','0','0','0','CONTEXT',49, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_M','ALT+M','','41','0','0','1','0','CONTEXT',50, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_M','SHFT+M','','41','0','1','0','0','CONTEXT',51, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_M','CTRL+M','','41','1','0','0','0','CONTEXT',52, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'N','N','','42','0','0','0','0','CONTEXT',53, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_N','ALT+N','','42','0','0','1','0','CONTEXT',54, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_N','SHFT+N','','42','0','1','0','0','CONTEXT',55, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_N','CTRL+N','','42','1','0','0','0','CONTEXT',56, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'O','O','','43','0','0','0','0','CONTEXT',57, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_O','ALT+O','','43','0','0','1','0','CONTEXT',58, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_O','SHFT+O','','43','0','1','0','0','CONTEXT',59, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_O','CTRL+O','','43','1','0','0','0','CONTEXT',60, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'P','P','','44','0','0','0','0','CONTEXT',61, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_P','ALT+P','','44','0','0','1','0','CONTEXT',62, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_P','SHFT+P','','44','0','1','0','0','CONTEXT',63, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_P','CTRL+P','','44','1','0','0','0','CONTEXT',64, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Q','Q','','45','0','0','0','0','CONTEXT',65, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Q','ALT+Q','','45','0','0','1','0','CONTEXT',66, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_Q','SHFT+Q','','45','0','1','0','0','CONTEXT',67, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_Q','CTRL+Q','','45','1','0','0','0','CONTEXT',68, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_R','ALT+R','','46','0','0','1','0','CONTEXT',69, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_R','SHFT+R','','46','0','1','0','0','CONTEXT',70, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_R','CTRL+R','','46','1','0','0','0','CONTEXT',71, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl+Shft+R','CTRL+SHFT+R','','46','1','1','0','0','CONTEXT',72, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'S','S','','47','0','0','0','0','CONTEXT',73, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_S','ALT+S','','47','0','0','1','0','CONTEXT',74, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_S','SHFT+S','','47','0','1','0','0','CONTEXT',75, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_S','CTRL+S','','47','1','0','0','0','CONTEXT',76, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'T','T','','48','0','0','0','0','CONTEXT',77, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_T','ALT+T','','48','0','0','1','0','CONTEXT',78, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_T','SHFT+T','','48','0','1','0','0','CONTEXT',79, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_T','CTRL+T','','48','1','0','0','0','CONTEXT',80, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'U','U','','49','0','0','0','0','CONTEXT',81, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_U','ALT+U','','49','0','0','1','0','CONTEXT',82, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_U','SHFT+U','','49','0','1','0','0','CONTEXT',83, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Ctrl_U','CTRL+U','','49','1','0','0','0','CONTEXT',84, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Z','Z','','54','0','0','0','0','CONTEXT',85, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Z','ALT+Z','','54','0','0','1','0','CONTEXT',86, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Shft_Z','SHFT+Z','','54','0','1','0','0','CONTEXT',87, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'Alt_Ctrl_Z','ALT+CTRL+Z','','54','1','0','1','0','CONTEXT',88, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'VolumeUp','VolumeUp','','24','0','0','0','0','CONTEXT',89, 'SUPER', GETDATE());
INSERT INTO key_code_master (uid ,key_name ,key_display_name,key_description,code, is_ctrl ,is_shift,is_alt,is_metakey ,type,sequence, CREATED_BY, CREATION_DATE) VALUES (NEWID() ,'VolumeDown','VolumeDown','','25','0','0','0','0','CONTEXT',90, 'SUPER', GETDATE());

 --Clean-up and Insert Script for adding user locale code
INSERT INTO locale (uid ,locale_code) VALUES(NEWID() ,'FR' );
INSERT INTO locale  (uid,locale_code) VALUES (NEWID() ,'EN');         
			          
-- Script for Version Master and Version Mapping for BFF Core , Admin and Mobile application
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1.0');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1.0.1');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1.0.2');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1.0.0');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'MOBILE_RENDERER', 0, '1.0.0.0');

INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'ADMIN_UI', 0, '1');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'ADMIN_UI', 0, '1.0');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'ADMIN_UI', 0, '1.0.1');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'ADMIN_UI', 0, '1.0.2');

INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'BFFCORE', 1, '1');
INSERT version_master (uid, created_by, creation_date, channel, active, version) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 'BFFCORE', 0, '1.0.0');

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'MOBILE_RENDERER' and version = '1'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'MOBILE_RENDERER' and version = '1.0'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'MOBILE_RENDERER' and version = '1.0.1'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'MOBILE_RENDERER' and version = '1.0.0'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'MOBILE_RENDERER' and version = '1.0.0.0'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'ADMIN_UI' and version = '1'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'ADMIN_UI' and version = '1.0'));

INSERT version_mapping (uid, created_by, creation_date, bffcore_version_id, mapped_app_id) VALUES (NEWID(), 'SUPER', SYSDATETIME(), 
(select uid from version_master where channel = 'BFFCORE' and active = 1),
(select uid from version_master where channel = 'ADMIN_UI' and version = '1.0.1'));