DELETE FROM resource_bundle where type='INTERNAL' and locale = 'fr-FR';

INSERT INTO resource_bundle (uid, locale ,resource_key  ,resource_value, type,created_by,creation_date)
	VALUES
		(NEWID(),'fr-FR','5001','Login authentication success_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5002','User logged in is authenticated_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9001','Login authentication failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9002','User access is not authorized_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9043','Login authentication failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9044','User authentication cannot be completed Authentication provider not responding._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6003','Login authentication failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6004','Authentication process failed to set/validate credentials_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9810','{0} version {1} is not compatible with {2} version {3}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5003','Flow created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5004','Flow created successfully with flowId : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9003','Flow creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9004','{0} is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6005','Flow creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6006','Flow creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9005','Flow creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9006','Flow creation failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5005','Flow updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5006','Flow updated successfully for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6007','Flow update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6008','Flow update failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9007','Flow update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9008','{0} is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9009','Flow update failed.Form name not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9010','{0} already exists. Form name is not unique for the flow._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9011','Flow update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9012','Flow update failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5007','Flow retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5008','Flow retrieved successfully for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6009','Flow not found_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6010','Flow not available for id : {0} _FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9013','Flow not found._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9014','Flow not available for id : {0} _FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9163','Flow is not published yet_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9164','Flow is disabled_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9180','Default form is disabled for this flow_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9181','Default form is not published yet for this flow_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9182','Flow has no default forms_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9183','Form not found_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5009','Flow status count retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5010','Flow status count retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6011','Flow status count retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6012','Flow status count retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9015','Flow status count retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9016','Flow status count retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5011','Flow list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5012','Flow list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6013','Flow retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6014','Flow retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9017','Flow retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9018','Flow retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5013','Flow unique validation done successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5014','{0} is unique._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5015','Successful checking of flow: _FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5016','{0} is not unique._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6015','Flow unique check validation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6016','Flow unique check validation failed for flow name : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5017','Flow deleted successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5018','Flow deleted successfully for flow id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6017','Flow deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6018','Flow deletion failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9019','Flow deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9020','Flow deletion failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5051','Form created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5052','Form created successfully with name : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9101','Form creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9102','Form name : {0} is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9103','Form creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9104','Form creation failed for name : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6101','Form creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6102','Form creation failed for name : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5053','Form updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5054','Form updated successfully for name : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9105','Form update is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9106','Form cannot be update.Form name : {0} is not unique._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9107','Form update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9108','Form update failed for name : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6103','Form update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6104','Form update failed for name : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5055','Form retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5056','Form retrieved successfully for Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9109','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9110','Form retrieved for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6105','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6106','Form retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5057','Form deleted successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5058','Form deleted successfully for Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9111','Form deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9112','Form deletion failed for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9113','Form deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9114','Form not available for Id : {0}._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6107','Form deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6108','Form deletion failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),  		   

		(NEWID(),'fr-FR','5101','Menu created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5102','Menu created successfully for Product Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5103','Menu deleted successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5104','Menu deleted successfully for Product Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5115','Menu updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5116','Menu updated successfully for Product Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5107','No Menus are found_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5108','No Menus are found_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6201','Menu creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6202','Menu creation failed for Product Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9201','Menu creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9202','Menu creation failed for Product Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5105','Menu retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5106','Menu retrieved successfully for Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5109','Menu retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5110','No Menus available_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6203','Menu retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6204','Menu retrieved failed for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9203','Menu retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9204','Menu retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9205','Menu name is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9206','Menu name is already used in the warehouse_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9207','Menu deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9208','Menu deletion failed for menuId : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6205','Invalid data supplied_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6206','Invalid Menu Type supplied_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6207','Invalid : Menu Trigger Action_FR','INTERNAL','SUPER',GETDATE()),
		 (NEWID(),'fr-FR','6208','Menu Unique Name Check encountered DataBase error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6209','Menu Trigger Action retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6210','Menu Trigger Action encountered DataBase error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6211','Menu Unique Name check retrieve unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6212','Trigger Action retrieval successful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6213','Menu Trigger Action retrieve unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6217','Menu deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6218','Menu deletion failed for menu Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9209','Menu Unique Name Check encountered  error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9210','Menu Trigger Action retrieval unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9211','Menu Trigger Action encountered  error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9213','Menu Unique Name check retrieval unsuccessful_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5151','Layer list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5152','Layer list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6301','Layer list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6302','Layer list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5153','User added to Layer successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5154','User added to Layer successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9251','User and Layer mapping failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9252','User and Layer mapping failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6303','User and Layer mapping failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6304','User and Layer mapping failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6913','User is already mapped to a Layer_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6914','User is already mapped to {0} Layer_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9954','User role mapping actionType is invalid_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9955','User role mapping actionType is invalid_FR','INTERNAL','SUPER',GETDATE()),		
		(NEWID(),'fr-FR','5656','User sucessfully mapped as a super user_FR','INTERNAL','SUPER',GETDATE()),				
		(NEWID(),'fr-FR','5657','User sucessfully mapped as a super user_FR','INTERNAL','SUPER',GETDATE()),						
		(NEWID(),'fr-FR','6915','User is already mapped as a super user_FR','INTERNAL','SUPER',GETDATE()),				
		(NEWID(),'fr-FR','6916','User is already mapped as a super user_FR','INTERNAL','SUPER',GETDATE()),	
		(NEWID(),'fr-FR','5181','User and Layer association deleted successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5182','User and Layer association deleted successfully_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5155','User and Layer association updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5156','User and Layer association updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9253','User and Layer mapping update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9254','User and Layer mapping update failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6305','User and Layer mapping update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6306','User and Layer mapping update failed due to  database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5157','User Role retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5158','User Role retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9255','User Role retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9256','User Role retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5159','User Permissions retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5160','User Permissions retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9257','User Permissions retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9258','Permissions retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()), 


		(NEWID(),'fr-FR','5201','Application Config retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5202','Application Config retrieved successfully for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9301','Application Config retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9302','Application Config retrieval failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6351','Application Config retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6352','Application Config retrieval failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5203','Dashboard flows retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5204','Dashboard flows retrieved successfully for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9303','Dashboard flows retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9304','Dashboard flows retrieval failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6353','Dashboard flows retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6354','Dashboard flows retrieval failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5205','Product Configuration retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5206','ProductConfig Id retrieved successfully for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9305','Product Configuration retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9306','Product Configuration retrieval failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6355','Product Configuration retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6356','Product Configuration retrieval failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5251','Custom Component created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5252','Custom Component created successfully with id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9401','Custom Component creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9402','Custom Component creation failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6401','Custom Component creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6402','Custom Component creation failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5253','Custom Component list retrieved Successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5254','Custom Component list retrieved Successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9403','Custom Component retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9404','Custom Component retrieval failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6403','Custom Component retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6404','Custom Component retrieval failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5255','Custom Component updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5256','Custom Component updated successfully for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9405','Custom Component update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9406','Custom Component update failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6405','Custom Component update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6406','Custom Component update failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5257','Custom Component deleted successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5258','Custom Component deleted successfully for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9407','Custom Component deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9408','Custom Component deletion failed for : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6407','Custom Component deletion failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6408','Custom Component deletion failed for : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5299','Registry list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5300','Registry list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9501','Registry list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9502','Registry list retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6501','Registry list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6502','Registry list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5301','Registry retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5302','Registry retrieved successfully for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9503','Registry retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9504','Registry retrieval failed for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6503','Registry retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6504','Registry retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5303','Registry created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5304','Registry created for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9505','Registry creation is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9506','Registry creation failed. Registry name {0} is not unique for the given API type and current layer_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9507','Registry creation is unsuccessful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9508','Registry creation failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6505','Registry creation is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6506','Registry creation failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5305','Registry updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5306','Registry updated for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9509','Registry update is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9510','Registry update failed. Registry name {0} is not unique for the given API type and current layer_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9511','Registry update is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9512','Registry update failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6507','Registry update is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6508','Registry update failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5307','Registry deleted successfully for action {0}._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5308','Registry deleted for id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9513','Registry deletion is unsuccessful for action {0}._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9514','Registry deletion failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6509','Registry deletion is unsuccessful for action {0}._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6510','Registry deletion failed for : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5309','API Master Registry list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5310','API Master Registry list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9515','API Master Registry list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9516','API Master Registry list retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6511','API Master Registry list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6512','API Master Registry list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5311','API Registry retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5312','API Registry retrieved successfully for registry Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9517','API Registry retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9518','API Registry retrieval failed for registry Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6513','API Registry retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6514','API Registry retrieval failed for registry Id : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5313','APIs retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5314','APIs retrieved successfully for id  : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9519','APIs retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9520','APIs retrieval failed for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6515','APIs retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6516','APIs retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		--validateUser
		(NEWID(),'fr-FR','5161','User validated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5162','User is a valid user_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9259','User validation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9260','User ID is invalid_FR','INTERNAL','SUPER',GETDATE()),

		--fetchAllForms
		(NEWID(),'fr-FR','5065','Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5066','Form list retrieved successfully for flow Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9125','Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9126','Form list retrieval failed for Id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6115','Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6116','Form list retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),		   

		--createDefaultForm
		(NEWID(),'fr-FR','5063','Form set as default successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5064','Form {0} set as default successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6113','Form set as default failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6114','Form set as default failed for id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9123','Form set as default failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9124','Form set as default failed for id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),

		--fetchOrphanForms
		(NEWID(),'fr-FR','5059','Orphan Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5060','Orphan Form list retrieved successfully for flow Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6109','Orphan Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6110','Orphan Form list retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9119','Orphan Form list retrieval is unsuccessful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9120','Orphan Form list retrieval is unsuccessful for Id : {0} encountered Database error._FR','INTERNAL','SUPER',GETDATE()),

		--fetchUnpublishForms
		(NEWID(),'fr-FR','5061','Unpublished Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5062','Unpublished Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9121','Unpublished Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9122','Unpublished Form list retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6111','Unpublished Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6112','Unpublished Form list retrieval failed due to Database error_FR','INTERNAL','SUPER',GETDATE()),	
		
		(NEWID(),'fr-FR','5069','Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5070','Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6119','Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6120','Form list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9149','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9150','Form retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5351','Registry created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5352','Registry created successfully with registryId : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','9601','Registry creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9602','Registry creation failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9956','Registry type is invalid_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9957','Registry type is invalid_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6601','Registry creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6602','Registry creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5353','Registry updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5354','Registry updated successfully for registry Id : {0}_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','9603','Registry update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9604','Registry update failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6603','Registry update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6604','Registry update failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5359','APIs override successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5360','APIs override successfully with below data_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','9605','APIs override failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9606','APIs override failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6607','APIs override failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6608','APIs override failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5355','Registry name is unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5356','{0} is unique_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6917','Registry name is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6918','Registry creation failed. Registry name {0} is not unique for the given API type and current layer_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5400','Resource bundle retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5401','Resource bundle entries retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6605','Registry name unique check failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6606','Registry name : {0} unique check failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5163','User Layer retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5164','User Layer retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6309','User Layer retrival failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6310','User Layer retrival failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9261','User layer retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9262','User is not assigned with any layer_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','9807','Authentication failed for channel : {0}._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9808','Authentication failed due to invalid channel : {0}_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9021','Flow update failed for flow name : {0}._FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9022','Flow update failed due to invalid action type : {0}_FR','INTERNAL','SUPER',GETDATE()),
	     	   
	    (NEWID(),'fr-FR','5019','Flow validated successfully for flow id : {0}._FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5020','Unpublished forms can be present in this flow. Still Do you want publish form flow? _FR','INTERNAL','SUPER',GETDATE()),
	   
	    (NEWID(),'fr-FR','5021','Flow published successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5022','Flow published successfully with flow id : {0}_FR','INTERNAL','SUPER',GETDATE()),

	      
		(NEWID(),'fr-FR','9023','Flow retrieval unsuccessful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9024','Flow retrieval unsuccessful as the flow with flowId: {0} is disabled._FR','INTERNAL','SUPER',GETDATE()),
		   
		   
		   (NEWID(),'fr-FR','5207','Defaultflow and Homeflow retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','5208','Defaultflow and Homeflow retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','9307','Defaultflow and Homeflow retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','9308','Defaultflow and Homeflow retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6357','Defaultflow and Homeflow retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6358','Defaultflow and Homeflow retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		   
		   (NEWID(),'fr-FR','6359','Home Flow not found_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6360','Home flow is disabled_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6361','Home flow is not published yet_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6362','Default form not found for home flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6363','Default form is disabled for home flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6364','Default form is not yet published for home flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6365','Default flow is disabled_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6366','Default flow is not published yet_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6367','Default form not found for default flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6368','Default form is disabled for default flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6369','Default form is not yet published for default flow_FR','INTERNAL','SUPER',GETDATE()),
		   (NEWID(),'fr-FR','6372','Default Flow not found_FR','INTERNAL','SUPER',GETDATE()),
	      (NEWID(),'fr-FR','6373','Default form of default flow is deleted_FR','INTERNAL','SUPER',GETDATE()),
	       (NEWID(),'fr-FR','6374','Default from of home flow is deleted_FR','INTERNAL','SUPER',GETDATE()),
		   
		  
		  (NEWID(),'fr-FR','5023','Flow disabled successfully_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','5024','Flow disabled successfully with flowId :{0}._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9025','Disable flow failed_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9026','Disable flow failed as the flow is the Default Flow._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9027','Disable flow failed_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9028','Disable flow failed as the flow is the Home Flow._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9029','Disable flow failed_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9030','Disable flow failed as the request type is invalid._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9031','disable flow failed_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9032','Disable flow failed as there are Forms under this flow._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','6019','Disable flow failed._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','6020','Disable flow failed due to database error._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9033','Disable flow failed._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9034','Disable flow failed due to system error._FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9160','Form is not published yet_FR','INTERNAL','SUPER',GETDATE()),
		  (NEWID(),'fr-FR','9161','Form is disabled_FR','INTERNAL','SUPER',GETDATE()),


		 --appconfig Creations

		(NEWID(),'fr-FR','5601','Context configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5602','Context configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5607','Global configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5608','Global configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5609','Application configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5610','Application configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5611','Internal configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5612','Internal configurations created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9901','Application configurations creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9902','Application configurations creation failed due to system  error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6901','Application configurations creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6902','Application configurations creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6907','Application configuration creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6908','Application configuration already exists for the supplied config type and name_FR','INTERNAL','SUPER',GETDATE()),

		 --fetch appconfig based on type and name

		(NEWID(),'fr-FR','5603','Application configuration retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5604','Application configuration retrieved successfully for Type and Name : {0} {1}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9903','Application configuration retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9904','Application configuration retrieval failed for : {0} {1} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6903','Application configuration retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6904','Application configuration retrieval failed for : {0} {1} due to database error_FR','INTERNAL','SUPER',GETDATE()),

		 --fetch appconfig based on type  
		 
		(NEWID(),'fr-FR','5605','Application configuration list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5606','Application configuration list retrieved successfully for type : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9905','Application configuration list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9906','Application configuration list retrieval failed for Type : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6905','Application configuration list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6906','Application configuration list retrieval failed for Type : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		--autocomplete appconfig based on type  

		(NEWID(),'fr-FR','5402','Application configuration retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5403','Application configuration retrieved successfully based on ConfigType Type : {0} search_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9703','Application configuration search failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9704','Application configuration search failed for Type : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6703','Application configuration search failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6704','Application configuration search failed for config type : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		--update appconfig Value 

		
		(NEWID(),'fr-FR','5613','Application configuration values updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5614','Application configuration values updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6909','Application configuration values update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6910','Application configuration values update failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9909','Application configuration values update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9910','Application configuration values update failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9913','Application configuration values update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9914','Application configuration values update failed as the name and type combination does not exist_FR','INTERNAL','SUPER',GETDATE()),
		
		-- ClearConfig Value
		(NEWID(),'fr-FR','5615','Application configuration values cleared successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5616','Application configuration values cleared successfully' ,'INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6911','Clearing Application configuration values failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6912','Clearing ConfigValue failed due to database error._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9911','Clearing Application configuration values failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9912','Clearing Application configuration values failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

		--Product API invocation
		(NEWID(),'fr-FR','5651','Product API invocation successful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5652','Product API invocation successful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9950','Product API invocation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9951','Product API invocation unsuccessful due to {0}_FR','INTERNAL','SUPER',GETDATE()),

		--fetchUnpublishOrphanForms
		(NEWID(),'fr-FR','5071','Unpublished Forms retrieval successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5072','Unpublished Forms retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5073','Orphan Forms retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5074','Orphan Forms retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9151','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9152','Form retrieval failed as the request type is invalid_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9153','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9154','Form retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),	
	    (NEWID(),'fr-FR','6121','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6122','Form retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
        
        --warehouselistapi
        (NEWID(),'fr-FR','5170','Warehouse list is retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5171','Warehouse details are fetched_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','6370','User Id is not present_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6371','Warehouse retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9165','Warehouse list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9166','Warehouse list encountered error._FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','6123','Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6124','Form list retrieval failed as the Flow with flow id : {0} is not available_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','6125','Form retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6126','No Forms available under the Flow_FR','INTERNAL','SUPER',GETDATE()),
		
		
		(NEWID(),'fr-FR','9170','Invalid Action type_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9171','Form Action type is invalid: {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9172','Flow Action type is invalid: {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9133','Invalid identifier_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9134','Form Identifier is invalid: {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9174','Flow Identifier is invalid: {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9135','Flow has default form already_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9136','Flow has default form already. Do you want to override: {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9137','Form cannot be disabled_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9138','Default form cannot be disabled_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9145','Form validated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9146','Do you want to publish form ?_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9173','Form is disabled. Do you still want to publish the form?_FR','INTERNAL','SUPER',GETDATE()),
		
		--publish forms
		(NEWID(),'fr-FR','5067','Form published successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5068','Form Published successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6117','Form publish failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6118','Form publish failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9147','Form publish failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9148','Form publish failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9414','Custom Control creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9415','Custom Control name is not unique : {0}_FR','INTERNAL','SUPER',GETDATE()),
		
		
      (NEWID(),'fr-FR','9080','Flow deletion failed_FR','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'fr-FR','9081','Default FormFlow cannot be deleted_FR','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'fr-FR','9082','Home FormFlow cannot be deleted._FR','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'fr-FR','9083','Formflow deletion will delete the forms inside it. Menus associated to the Formflow should be updated manually_FR','INTERNAL','SUPER',GETDATE()),
	  (NEWID(),'fr-FR','9084','Formflow validated successfully_FR','INTERNAL','SUPER',GETDATE()),
	  
	    (NEWID(),'fr-FR','5029','Flow Extended successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5030','Flow Extended successfully with flowId : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5047','Flow cloned successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5048','Flow cloned successfully with flowId : {0}_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9046','Flow Extension creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9047','{0}, Extended Flow Name is not unique_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6025','Flow Extension creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6026','Flow Extension creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','6033','Cloning of flow failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6034','Cloning of flow failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9048','Flow Extension creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9049','Flow Extension creation failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9066','Cloning of flow failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9067','Cloning of flow failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9070','Flow version creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9071','Flow version created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9072','Flow version creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9073','Flow version creation failed due to system error_FR','INTERNAL','SUPER',GETDATE()),

	    (NEWID(),'fr-FR','5035','Form Extended successfully_FR','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'fr-FR','5036','Form Extended successfully with formId : {0} within the same flow_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5037','Form Extended successfully_FR','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'fr-FR','5038','Form Extended successfully with formId : {0} in the different flow_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9054','Extending component Unsuccessful._FR','INTERNAL','SUPER',GETDATE()),
        (NEWID(),'fr-FR','9055','Extending component Unsuccessful as the request type is Invalid._FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9056','Form Extension creation failed_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9057','{0}, Extended form Name is not unique_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5031','Flow Extension retrieved successfully._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5032','Flow Extension difference retrieved successfully for parent : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5033','Flow Extension cannot retrieved successfully._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5034','Flow Extension difference cannot be retrieved for parent : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9050','Flow Extension history retrieval is encountered error._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9051','Flow Extension retrieval is unsuccessful for extension type : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6027','Flow Extension history retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6028','Flow Extension history retrieval failed for object id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9052','Flow Extension history retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9053','Flow Extension history retrieval failed for object id : {0} due to system error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5452','Resource bundle retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5453','Resource bundles based on locale and type retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9803','Resource bundle retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9804','Resource bundle retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6803','Resource bundle retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6804','Resource bundle retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),	   
		(NEWID(),'fr-FR','5450','Resource bundle created successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5451','Resource bundle created successfully with id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6801','Resource bundle creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6802','Resource bundle creation failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9801','Resource bundle creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9802','Resource bundle creation failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'fr-FR','6807','Resource bundle creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6808','Resource bundles based on locale and key pair is already exist_FR','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'fr-FR','6809','Resource bundle creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6810','Resource bundles resource key is not allowed to empty string_FR','INTERNAL','SUPER',GETDATE()),
		   
		(NEWID(),'fr-FR','9129','Invalid Identifier_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9130','Invalid Identifier passed while marking default_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9128','Flow has already default form associated_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9127','Creating default form failed_FR','INTERNAL','SUPER',GETDATE()),
		     
		(NEWID(),'fr-FR','5653','File imported successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5654','All Files Imported Successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5659','Imported data saved successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5660','All files imported are saved successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5661','All files imported are published successfully_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9952','File import failed_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9953','File import failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9960','File import failed for {0}_FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','9961','File Import failed for {0}. Empty Upload file is not allowed_FR','INTERNAL','SUPER',GETDATE()),		  
   	    (NEWID(),'fr-FR','9967','Data save failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9968','Imported data failed during save due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9969','Import data check violated_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9970','Rules to import data violated. {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9971','File Import should be from root folder_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9972','Nested folder file import is not allowed, File import should be from root folder. {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5701','Comparison disallowed for {0}._FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5702','This {0} requested for comparison is newly added in the extended form and doesn’t exist in the parent form_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5709','Comparison failed for {0}._FR','INTERNAL','SUPER',GETDATE()),
	    (NEWID(),'fr-FR','5710','Parent field is missing to compare._FR','INTERNAL','SUPER',GETDATE()),
	    
		(NEWID(),'fr-FR','5039','Flow basic details retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5040','Flow basic details retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9058','Flow basic details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9059','Flow basic details retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6029','Flow basic details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6030','Flow basic details retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5801','Locale updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5802','Locale updated successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5803','Invalid Locale supplied._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5804','Invalid Locale supplied._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5805','Locale update encountered database error._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5806','Locale update encountered database error._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5807','Locale update failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5808','Locale update failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5500','Flow is deleted_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5502','Form is deleted._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5504','Default form is not available for this flow_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5506','Custom Control is deleted_FR','INTERNAL','SUPER',GETDATE()),

		
		(NEWID(),'fr-FR','5111','Invalid product name_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5112','Warehouse name is not valid_FR','INTERNAL','SUPER',GETDATE()),
		
		
		--fetchOrphanForms
		(NEWID(),'fr-FR','5080','Custom Component Form list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5081','Custom Component Form list retrieved successfully for flow Id : {0}_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6150','Custom Component Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6151','Custom Component Form list retrieval failed for Id : {0} due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9155','Custom Component Form list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9156','Custom Component Form list retrieval failed for Id : {0} due to system error._FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','5025','Logout successful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5026','User Logged out Successfully_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','6214','Invalid Request_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6215','Product Name or Default warehouse is mandatory_FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','9409','Custom Control validation successful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9410','Custom Control is linked with forms , Do you still want to delete ?_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9411','Custom Control validation successful_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9412','Do you want to delete ?_FR','INTERNAL','SUPER',GETDATE()),
		
		--fetch hotkeys
		
		(NEWID(),'fr-FR','5703','Hot key list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5704','Hot key list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9958','Hot key list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9959','Hot key list retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6919','Hot key list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6920','Hot key list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		
			--fetch user language codes
		
		(NEWID(),'fr-FR','5705','User language code list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5706','User language code list retrieved successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9962','User language code list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9963','User language code list retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6921','User language code list retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6922','User language code list retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		
		-- Pre and Post processor file upload
		(NEWID(),'fr-FR','9964','Both pre and post processor files are empty_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9965','{0} processor file upload failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6923','{0} processor file upload failed due to database error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5707','{0} processor file uploaded successfully_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9966','API has already {0} processor file_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5708','API do not have any {0} processor file_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5041','Flow with Default Form details retrieval Successful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5042','Flow with Default Form details retrieved Successfully._FR','INTERNAL','SUPER',GETDATE()),		
		(NEWID(),'fr-FR','9060','Flow with Default Form details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9061','Flow with Default Form details retrieval failed as Flow Permissions are Invalid_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9062','Flow with Default Form details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9063','Flow with Default Form details retrieval failed due to system error_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9064','Form details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9065','Form details retrieval Unsuccessful as the Flow with id : {0} has No Permissions._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6031','Flow with Default Form details retrieval failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6032','Flow with Default Form details retrieval failed due to database error_FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5043','Tenant session inactive period retrival Successful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5044','Tenant session inactive period retrived Successfully._FR','INTERNAL','SUPER',GETDATE()),

		(NEWID(),'fr-FR','5045','Tenant session inactive period modified Successful._FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','5046','Tenant session inactive period modified Successfully._FR','INTERNAL','SUPER',GETDATE()),
		
		(NEWID(),'fr-FR','6609','Registry creation failed_FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6610','Uploading Swagger file is either in Invalid Format or Open API Version is not supported _FR','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','6611','Third party API - Host is mandatory_FR','INTERNAL','SUPER',GETDATE()),
		
		-- Product validity check during login/auth
		(NEWID(),'fr-FR','9973','Invalid product {0}_FR.','INTERNAL','SUPER',GETDATE()),
		(NEWID(),'fr-FR','9974','Invalid product {0} supplied. This product is not supported by current instance of BFFCORE_FR.','INTERNAL','SUPER',GETDATE());		