CREATE TABLE SESSION_MANAGEMENT (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100)
	CONSTRAINT SESSION_MANAGEMENT_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SESSION_MANAGEMENT_IX1 ON SESSION_MANAGEMENT (SESSION_ID);
CREATE INDEX SESSION_MANAGEMENT_IX2 ON SESSION_MANAGEMENT (EXPIRY_TIME);
CREATE INDEX SESSION_MANAGEMENT_IX3 ON SESSION_MANAGEMENT (PRINCIPAL_NAME);

CREATE TABLE SESSION_MANAGEMENT_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES IMAGE NOT NULL,
	CONSTRAINT SESSION_MANAGEMENT_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SESSION_MANAGEMENT_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SESSION_MANAGEMENT(PRIMARY_ID) ON DELETE CASCADE
);